policy-name:
  when:
    kind: "status"
    subject: "cron.service"
    payload: "enabled"
  then:
      script: 
        name: "hello_world"
        args:
          - $subject
          - $payload 
        