oled:
  enabled: true
  driver: "sh1106"
  device: "/dev/12c-1"
  width: 128
  height: 64
  font_size: 11

push:
  enabled: true
  ntfy:
    server: "https://ntfy.sh"
    auth: null
  gotify:
    server: "https://localhost:8080"
    token: null # "TOKEN" if applies
  webhook:
    #url: "https://discord.com/api/webhooks/11111111/ANYYYYYYYYYYYYYYYYYYYYYYYYYY"
    headers:
      Authorization: null #"Bearer TOKEN"  if applies