enabled: null

scope:
  auto: true
  cidr: null
  interface: null

monitoring:
  devices: true
  traffic: true

detection:
  scans: true
  dos: true
  dns: true
  risky_services:
    enabled: true
    suspicious:
      include: []
      exclude: []
  risky_ports:
    enabled: true
    suspicious:
      include: []
      exclude: []
  vulnerabilities: true
  scanning: "passive" # "passive"/"active"

intelligence:
  enabled: true
